FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.3
RUN mkdir -p /usr/share/elasticsearch/config/ingest-geoip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch repository-s3
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin list
